
# When changing bucket name, make sure to also edit minio.dfeaultBucket.name to reflect
# the same values, or else the bucket won't be created for you
bucketName: kolibri-studio-storage

# The django settings for both studio-app and studio workers
settings: contentcuration.settings


studioApp:
  appPort: 8081
  imageName: gcr.io/github-learningequality-studio/app:nlatest
  replicas: 1
  type: NodePort
  postmarkApiKey:
  ingress:
    enabled: true
  gDrive:
    keyJson:


studioNginx:
  imageName: learningequality/contentworkshop-app-nginx-proxy:v4
  port: 8080


studioWorkers:
  replicas: 1


postgresql:
  internalDBEnabled: true
  postgresUser: learningequality
  postgresDatabase: devDB
  postgresPassword: notsecure
  persistence:
    size: 2Gi
  externalCloudSQL:
    enabled: false
    proxyHostName:


minio:
  internalMinioEnabled: true
  externalGoogleCloudStorage:
    enabled: false
    gcsKeyJson:
  service:
    port: 9000
  persistence:
    size: 5Gi
  defaultBucket:
    enabled: true
    policy: download
    name: kolibri-studio-storage


redis:
  internalRedisEnabled: true
  password: notsecure

sentry:
  dsnKey:

studioProber:
  imageName: gcr.io/github-learningequality-studio/prober:nlatest
  newrelicKey:
  newrelicAccountId:
  port: 9313
