---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "studio.fullname" . }}-db-migrate-config
  labels:
    app: {{ template "studio.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings }}
  DJANGO_LOG_FILE: /var/log/django.log
  DATA_DB_PORT: "5432"
  MPLBACKEND: PS
  STUDIO_BETA_MODE: "yes"
  RUN_MODE: k8s
  RELEASE_COMMIT_SHA: {{ .Values.studioApp.releaseCommit | default "" }}
  BRANCH_ENVIRONMENT: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}-db-migrate-secrets
  labels:
    app: studio
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  DATA_DB_HOST: {{ .Values.postgresql.externalCloudSQL.proxyHostName | default (include "postgresql.fullname" .) | b64enc }}
  DATA_DB_NAME: {{ .Values.postgresql.postgresDatabase | default "" | b64enc }}
  DATA_DB_USER: {{ .Values.postgresql.postgresUser | default "" | b64enc }}
  DATA_DB_PASS: {{ .Values.postgresql.postgresPassword | default "" | b64enc }}
  SENTRY_DSN_KEY: {{ .Values.sentry.dsnKey | default "" | b64enc }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "studio.fullname" . }}-migrate-job
  labels:
    app: {{ template "studio.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: dbmigrate
        image: {{ .Values.studioApp.imageName }}
        command:
        - make
        - migrate
        envFrom:
        - configMapRef:
            name: {{ template "studio.fullname" . }}-db-migrate-config
        - secretRef:
            name: {{ template "studio.fullname" . }}-db-migrate-secrets
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: contentcuration.migration_production_settings
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
