---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "studio.fullname" . }}-prober-service
  labels:
    app: {{ template "studio.fullname" . }}-prober
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.studioProber.port }}
  selector:
    app: {{ template "studio.fullname" . }}-prober
  type: NodePort
