---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "studio.fullname" . }}-app
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.studioNginx.port }}
  selector:
    app: {{ template "studio.fullname" . }}
    tier: app
  type: NodePort
