apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    app: studio
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postmark-api-key: {{ .Values.studioApp.postmarkApiKey | default "" | b64enc }}
  redis-password: {{ .Values.redis.password | default "" | b64enc }}
  postgres-user: {{ .Values.postgresql.postgresUser | default "" | b64enc }}
  postgres-password: {{ .Values.postgresql.postgresPassword | default "" | b64enc }}
  postgres-database: {{ .Values.postgresql.postgresDatabase | default "" | b64enc }}
  {{ if .Values.sentry.dsnKey }}
  sentry-dsn-key: {{ .Values.sentry.dsnKey }}
  {{ end }}
  {{ if .Values.studioProber.newrelicKey }}
  newrelic-key: !!str {{ .Values.studioProber.newrelicKey | default "" | b64enc }}
  newrelic-account-id: !!str {{ .Values.studioProber.newrelicAccountId | default "" | b64enc}}
  {{ end }}
